const projects = [
	{
		id: 1,
		name: "Great Outdoors Guide",
		about: "Plan your next adventure to in the U.S. National Parks!",
		phase: 4,
		link: "https://great-outdoors-guide.netlify.app",
		image: "https://i.imgur.com/8GnP2Uw.png",
		claps: 0,
	},
	{
		id: 2,
		name: "Book Her",
		about:
			"The app takes you (the Casting Director) through a series of questions to determine the Models you need for your next Project.",
		phase: 2,
		link: "https://bookher.netlify.app/new_project",
		image: "https://i.imgur.com/INs84Uk.png",
		claps: 1,
	},
	{
		id: 3,
		name: "Code Bucket",
		about: "Web-based CSS, JS and HTML Editor",
		phase: 4,
		link: "https://code-bucket.netlify.app",
		image: "https://i.imgur.com/Hz84TA2.png",
		claps: 0,
	},
	{
		id: 11,
		name: "Yourseum",
		about: "Find great art",
		phase: 4,
		link: "https://yourseum.netlify.app",
		image: "https://i.imgur.com/yywQCoi.png",
		claps: 0,
	},
	{
		id: 12,
		name: "Spreddit",
		about: "A Global Community of Like Minded Humans Socially Distancing ",
		phase: 4,
		link: "https://spreddit.netlify.app",
		image: "https://i.imgur.com/cyZCpWs.png",
		claps: 0,
	},
	{
		id: 13,
		name: "snackATTACK",
		about: "It's Time to Discover",
		phase: 4,
		link: "https://snackattack.netlify.app",
		image: "https://i.imgur.com/VTJB4qy.png",
		claps: 0,
	},
	{
		id: 20,
		name: "YouTravel",
		about: "YouTube for Travel Videos",
		phase: 3,
		link: "https://youtravel.netlify.app/",
		image: "https://i.imgur.com/Y6mlORn.png",
		claps: 0,
	},
	{
		id: 22,
		name: "Breathe",
		about: "Meditation",
		phase: 3,
		link: "https://github.com/maifam/breathe_frontend",
		image: "https://i.imgur.com/hAuKx3K.png",
		claps: 0,
	},
	{
		id: 23,
		name: "HomeStory",
		about:
			"A web app for storing info about furniture items you plan on purchasing in the future or simply just want to keep tabs of.",
		phase: 3,
		link: "https://homestory.netlify.app",
		image: "https://i.imgur.com/il8ft21.png",
		claps: 0,
	},
	{
		id: 24,
		name: "Locksley To Do",
		about: "A todo list and calendar app",
		phase: 4,
		link: "https://www.locksleyr.com",
		image: "https://i.imgur.com/XOnaclL.png",
		claps: 0,
	},
	{
		id: 25,
		name: "GamesRx",
		about: "Game info and reviews",
		phase: 3,
		link: "https://gamesrx.netlify.app",
		image: "https://i.imgur.com/Japzh6v.png",
		claps: 9,
	},
	{
		name: "Three.js",
		about:
			"Three.js is a cross-browser JavaScript library and application programming interface used to create and display animated 3D computer graphics in a web browser using WebGL.",
		phase: 5,
		link: "https://threejs.org/",
		image: "https://discoverthreejs.com/images/threejs_site_screenshot.jpg",
		claps: 3,
		id: 28,
	},
	{
		name: "Unseen Studios",
		about:
			"We help brands transform by blending meaningful branding, compelling digital experiences and motion productions.",
		phase: 5,
		link: "https://unseen.co/",
		image:
			"https://assets.awwwards.com/awards/sites_of_the_day/2023/02/unseen-studio-1.jpg",
		claps: 0,
		id: 29,
	},
	{
		name: "Nike",
		about:
			"The world's largest athletic apparel company, Nike is best known for its footwear, apparel, and equipment.",
		image:
			"https://assets.fontsinuse.com/static/use-media-items/44/43115/full-1190x905/57c69580/Nike02.jpeg",
		claps: 0,
		link: "https://www.nike.com/",
		phase: 0,
		id: 30,
	},
	{
		name: "Netflix",
		about:
			"Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries, and more.",
		image:
			"https://miro.medium.com/v2/resize:fit:1400/1*8BtlgpxyjOPaLZXO6pVD0Q.jpeg",
		claps: 1,
		link: "https://www.netflix.com/",
		phase: 5,
		id: 32,
	},
];

export default projects;
